steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  entrypoint: bash
  args:
    - -c
    - |
      docker build . -t europe-west3-docker.pkg.dev/$PROJECT_ID/webapp/wordblend:latest \
      && docker push europe-west3-docker.pkg.dev/$PROJECT_ID/webapp/wordblend:latest \
  secretEnv: ['AOSS_KEY']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  id: Deploy API
  args: ['run', 'deploy', $PROJECT_ID,
             --image=europe-west3-docker.pkg.dev/$PROJECT_ID/webapp/wordblend:latest,
             '--region=europe-west3', '--service-account=firebase-adminsdk-jfp0o@wordblend-ai.iam.gserviceaccount.com',
              '--allow-unauthenticated',
              '--vpc-connector=serverless-vpc-connector1',
              '--set-env-vars=FLASK_APP=main.py,PRODUCTION=True,BASE_URL=wordblend-ai-zglzosebja-ey.a.run.app,GCP_PROJECT=wordblend-ai,API=true,REDIS_IP=10.42.53.6',
              '--set-secrets=WORDBLEND_OAUTH_CLIENT_SECRET_JSON=WORDBLEND_OAUTH_CLIENT_SECRET_JSON:latest,WORDBLEND_SERVICE_ACCOUNT_KEY_JSON=WORDBLEND_SERVICE_ACCOUNT_KEY_JSON:latest,GOOGLE_OAUTH_CLIENT_ID=GOOGLE_OAUTH_CLIENT_ID:latest,GOOGLE_OAUTH_CLIENT_SECRET=GOOGLE_OAUTH_CLIENT_SECRET:latest']
  waitFor: [ 'Build' ]

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Deploy Cloud Run worker job
  entrypoint: gcloud
  args: ['beta', 'run', 'jobs', 'replace', './worker/knative-deploymnet.yaml', '--region=europe-west3']
  waitFor: ['Build']

- name: "gcr.io/cloud-builders/gcloud"
  id: Deploy Cloud FirestoreUpdater Cloud Function
  args: ["functions", "deploy", "update-firestore-function", "--runtime", "python310", "--entry-point",
         "firestore_updater_cloud_function", "--trigger-bucket", "wordblend-ai-generated-pictures-public",
         "--service-account", "update-firestore-function-sa@wordblend-ai.iam.gserviceaccount.com",
         "--vpc-connector=serverless-vpc-connector1",
         "--set-env-vars=REDIS_IP=10.42.53.6",
         "--region=europe-west3", "--source=./firestore_updater_cloud_function"]
  env: ["PROJECT_ID=wordblend-ai"]
  waitFor: ['-']

availableSecrets:
  secretManager:
  - versionName: projects/966921858684/secrets/AOSS_KEY/versions/latest
    env: 'AOSS_KEY'
options:
  logging: CLOUD_LOGGING_ONLY

images:
- 'europe-west3-docker.pkg.dev/$PROJECT_ID/webapp/wordblend:latest'